### ISSUE TITLE
Is this Repo still active?

### ISSUE THREAD

**Issue by jerairrest** [boourns/go_shopify#2]
I would love to use a go-shopify package without writing my own.

**Comment by boourns** [comment]
It functions, but isn't maintained.  Many endpoints and actions are missing, but are easy to add if you fork.

It seems most people have started with this, then modified it to suit their tastes and not submitted their patches back, judging by activity at https://github.com/boourns/go_shopify/network.

**Comment by jerairrest** [comment]
Gotcha! A great alternative to this package that im currently using / adding to as needed is https://github.com/getconversio/go-shopify thanks again!
